name: shebirth
description: Production

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"
string_capitalize:
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  youtube_player_iframe:
  font_awesome_flutter:
  provider: ^6.0.1
  dio: ^4.0.3
  table_calendar:
  syncfusion_flutter_datepicker:
  google_fonts: ^2.3.0
  shared_preferences:
  intl: ^0.17.0
  file_picker:
  open_file:
  fl_chart:
  url_launcher: ^6.0.17
  http:
  razorpay_flutter: ^1.1.4
  string_capitalize:
  image_picker:
  carousel_slider:
  video_player: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Group 1212.png
    - assets/pregnant.png
    - assets/Path 1295.png
    - assets/no-fat.png
    - assets/heart.png
    - assets/baby.png
    - assets/Group 1213.png
    - assets/Client dummy.png
    - assets/Group 1214.png
    - assets/Motherhood-bro.png
    - assets/medicalRecord.png
    - assets/dummy.png
    - assets/Consultant.png
    - assets/dummy display1.jpg
    - assets/Background.png
    - assets/appbar.jpeg
    - assets/Sample.mp4
    - assets/Diet.png
    - assets/PregnancyConcern.png
    - assets/Meditation.png
    - assets/Relaxation.png
    - assets/Planning Birth.png
    - assets/Lactation.png
    - assets/Newborn.png
    - assets/DeliveryProcess.png
    - assets/WhatsApp Image 2022-02-23 at 16.50.53.jpeg
    - assets/Skill Set.png
    - assets/med.png
    - assets/hinduist-yoga-position.png
    - assets/Breathing.png
    - assets/Affirmation.png
    - assets/execise.png
    - assets/coffeee.png
    - assets/activity.png
    - assets/contractions.png
    - assets/StayFit.png
    - assets/symp.png
    - assets/Shebirth Final Logo new.png
    - assets/Background.png
    - assets/daily tracker.png
    - assets/labor portal.png
    - assets/learning.png
    - assets/Morning.png
    - assets/Breakfast.png
    - assets/Mornig Snack.png
    - assets/Lunch.png
    - assets/Evening Snack.png
    - assets/Dinner.png
    - assets/Dinner Drink.png
    - assets/Group 3514(1).png
    - assets/counterstop.png
    - assets/counterstart.png
    - assets/natural.png
    - assets/Path 1103.png
    - assets/banner.png
    - assets/banner1.png
    - assets/ScanIcon.png
    - assets/TermIcon.png
    - assets/demo video.mp4